<?php use LipePool\Security\Csrf; use LipePool\Support\View; ?>
<section class="page-heading container"><p class="eyebrow">Área administrativa</p><h1>Serviços</h1><p class="lead">Cadastre e mantenha o catálogo disponível para novas solicitações.</p><a class="text-link" href="/admin/agenda">← Voltar para agenda</a></section>
<section class="container section admin-service-layout">
    <div class="form-card service-create-card"><h2>Novo serviço</h2><form method="post" action="/admin/servicos" class="stack-form"><input type="hidden" name="_csrf" value="<?= View::escape(Csrf::token()) ?>"><label>Nome<input name="name" maxlength="120" required></label><label>Descrição <span class="muted">(opcional)</span><textarea name="description" maxlength="1000" rows="3"></textarea></label><label>Duração em minutos <span class="muted">(opcional)</span><input name="duration_minutes" type="number" min="1" max="1440"></label><button class="button button-primary" type="submit">Criar serviço</button></form></div>
    <div class="service-admin-list"><h2>Catálogo atual</h2>
        <?php if (!$services): ?><div class="empty-state"><p>Nenhum serviço cadastrado.</p></div><?php endif; ?>
        <?php foreach ($services as $service): ?><article class="service-admin-card <?= (int)$service['is_active'] === 1 ? '' : 'is-inactive' ?>">
            <div class="section-heading-row"><h3><?= View::escape($service['name']) ?></h3><span class="status <?= (int)$service['is_active'] === 1 ? 'status-completed' : 'status-cancelled' ?>"><?= (int)$service['is_active'] === 1 ? 'Ativo' : 'Inativo' ?></span></div>
            <?php if ((int)$service['is_active'] === 1): ?><form method="post" action="/admin/servicos/<?= (int)$service['id'] ?>/atualizar" class="stack-form"><input type="hidden" name="_csrf" value="<?= View::escape(Csrf::token()) ?>"><label>Nome<input name="name" maxlength="120" value="<?= View::escape($service['name']) ?>" required></label><label>Descrição<textarea name="description" maxlength="1000" rows="3"><?= View::escape($service['description'] ?? '') ?></textarea></label><label>Duração em minutos<input name="duration_minutes" type="number" min="1" max="1440" value="<?= View::escape($service['duration_minutes'] ?? '') ?>"></label><div class="button-row"><button class="button button-primary button-small" type="submit">Salvar</button></div></form><form method="post" action="/admin/servicos/<?= (int)$service['id'] ?>/desativar" class="deactivate-form"><input type="hidden" name="_csrf" value="<?= View::escape(Csrf::token()) ?>"><button class="button button-danger button-small" type="submit">Desativar serviço</button><small>O histórico permanece salvo.</small></form><?php else: ?><p class="muted">Serviço inativo; os agendamentos associados continuam no histórico.</p><?php endif; ?>
        </article><?php endforeach; ?>
    </div>
</section>
